multiple changes

diff --git a/bin/cfmm2tar b/bin/cfmm2tar
--- a/bin/cfmm2tar
+++ b/bin/cfmm2tar
@@ -1,5 +1,17 @@
 #!/bin/bash
 
+execpath=`dirname $0`
+execpath=`realpath $execpath`
+
+
+source ${NEUROGLIA_BASH_LIB}
+if [ ! "$?" = 0 ]
+then
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
+fi
+
+
 
 cfmm2tar_img=`shub-cache shub://khanlab/cfmm2tar:v0.0.1i`
 
diff --git a/bin/joblistSubmit b/bin/joblistSubmit
--- a/bin/joblistSubmit
+++ b/bin/joblistSubmit
@@ -1,8 +1,19 @@
 #!/bin/bash
 
+execpath=`dirname $0`
+execpath=`realpath $execpath`
 
-if [ "$#" -lt 1 ]
-then 
+
+source ${NEUROGLIA_BASH_LIB}
+if [ ! "$?" = 0 ]
+then
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
+fi
+
+
+function usage {
+
    echo""
    echo "=========================================================================="
    echo "Interface for running list of jobs on cluster"
@@ -17,18 +28,30 @@ then
    echo ""
    echo " -t : test-mode, don/'t actually submit any jobs"
    echo " -e : preserve environment variables (--export=ALL to sbatch)"
+   echo " -A <account> : account to use for allocation (default: $CC_COMPUTE_ALLOC)"
+   echo " -E <env_script>:  script to source for env setup"
    echo ""
-   echo " Required resources:"
-   echo " -j <job-template> :  sets requested resources"
-   echo "	Regular (default):	8core/32gb/24h"
-   echo "	LongSkinny:		1core/4gb/72h"
-   echo "	ShortFat:		32core/128gb/3h"
-   echo ""
-   echo " SLURM Job dependencies for pipelining (man sbatch for more details):"
-   echo "  -d aftercorr:jobid[:jobid]	: each subj depends on completed subj in submitted job ids"  
-   echo "  -d afterok:jobid[:jobid]	: each subj depends on all completed subj in submitted job id"
-   echo ""
+   usage_job_templates
+   usage_job_depends
 
+ }
+
+
+#get options in front 
+while getopts "J" options; do
+ case $options in
+    J ) print_job_templates
+	exit 1;;
+    * ) usage
+	exit 1;;
+ esac
+done
+
+shift $((OPTIND-1))
+
+if [ "$#" -lt 1 ]
+then 
+  usage
   exit 1
 fi
 
@@ -41,9 +64,13 @@ job_template=Regular
 depends=""
 testmode=0
 keepenv=0
+cc_account=$CC_COMPUTE_ALLOC
+envscript=
 
-while getopts "j:td:e" options; do
+while getopts "Jj:td:eA:E:" options; do
  case $options in
+    J ) print_job_templates
+	exit 1;;
     j ) echo "	Using job template: $OPTARG" >&2
 	job_template=$OPTARG;;
     d ) echo "	Using dependencies: $OPTARG" >&2
@@ -52,7 +79,11 @@ while getopts "j:td:e" options; do
 	testmode=1;; 
     e ) echo "	Preserve environment (--export=ALL)" >&2
 	keepenv=1;;
-    * ) usage
+    A ) echo "	Using allocation account: $OPTARG" >&2
+	    cc_account=$OPTARG;;
+    E ) echo "	Sourcing $OPTARG in each job" >&2
+	envscript=$OPTARG;;
+   * ) usage
 	exit 1;;
  esac
 done
@@ -77,13 +108,19 @@ job=$job_dir/$jobname.job
 
 execpath=`dirname $0`
 execpath=`realpath $execpath`
-cp $execpath/job-templates/${job_template}.job $job  
+cp ${NEUROGLIA_DIR}/job-templates/${job_template}.job $job  
 
 echo "#SBATCH --job-name=$jobname" >> $job
+echo "#SBATCH --account=$cc_account" >> $job
 
 #submit with array, using subj and subjlist, indexed by line number (1-N)
 echo "#SBATCH --output=$job_dir/${jobname}.%A_%a.out" >> $job
 echo "#SBATCH --array=$indices" >> $job
+
+if [ -n "$envscript" ]
+then
+	echo "source $envscript" >> $job
+fi
 
 echo "cmd=\`head -n \$SLURM_ARRAY_TASK_ID `realpath $joblist`  | tail -n 1\`" >> $job
 echo cd `pwd` >> $job
diff --git a/bin/neurogliaBatch b/bin/neurogliaBatch
--- a/bin/neurogliaBatch
+++ b/bin/neurogliaBatch
@@ -1,25 +1,42 @@
 #!/bin/bash
-host=`hostname`
-if [ ! ${host:0:3} == "gra" ]
+
+
+execpath=`dirname $0`
+execpath=`realpath $execpath`
+
+
+source ${NEUROGLIA_BASH_LIB}
+if [ ! "$?" = 0 ]
 then
-	echo "Please ssh to graham.sharcnet.ca before using $0" >&2
+	echo "Error initializing neuroglia-helpers, quitting $0"
 	exit 1
 fi
+
 
 
 
 #run a pipeline job on the cluster
 #pipeline jobs take subjids as args
 
+#if [ ! -n "$SINGULARITY_IMG" ]
+#then
+#	echo "SINGULARITY_IMG not defined! exiting..." >&2
+#	exit 1
+#fi
+
+if [ ! -n "$SINGULARITY_OPTS" ]
+then
+	echo "SINGULARITY_OPTS not defined! exiting..." >&2
+	exit 1
+fi
+
 cmd=$0
 cmdname=${cmd##*/}
 
-
-if [ "$#" -lt 2 ]
-then 
+function usage {
    echo""
    echo "=========================================================================="
-   echo "Interface for running pipeline scripts on the cluster "
+   echo "Interface for running pipeline scripts on the cluster with singularity"
    echo ""
    echo "  Loops through an input subject_list_txt (txt with subj id on each line)"
    echo "  Can be used to run scripts that generally take command-line parameters as:"
@@ -35,24 +52,34 @@ then
    echo " -g : group/reduce job, pass the subject list instead of looping over subjects"
    echo " -s <subjid> : single-subject mode, run on a single subject (must be in subjlist) instead"
    echo " -t : test-mode, don/'t actually submit any jobs"
+   echo " -A <account> : account to use for allocation (default: $CC_COMPUTE_ALLOC)"
+   echo " -N <name> : name the batch job (default: name is command with path stripped off)"
+   echo " -U <uri> : uri for singularity container to use (default: $NEUROGLIA_URI)"
+   echo " -I <simg> : path to container to use (default: `shub-cache $NEUROGLIA_URI`)"
    echo ""
-   echo " Required resources:"
-   echo " -j <job-template> :  sets requested resources"
-   echo "	Regular (default):	8core/32gb/24h"
-   echo "	LongSkinny:		1core/4gb/72h"
-   echo "	ShortFat:		32core/128gb/3h"
-   echo ""
-   echo " Passing arguments to pipeline script"
-   echo "  -b /"args/" : cmd-line arguments that go *before* the subject id"
-   echo "  -a /"args/" : cmd-line arguments that go *after* the subject id"
-   echo ""
-   echo " SLURM Job dependencies for pipelining (man sbatch for more details):"
-   echo "  -d aftercorr:jobid[:jobid]	: each subj depends on completed subj in submitted job ids"  
-   echo "  -d afterok:jobid[:jobid]	: each subj depends on all completed subj in submitted job id"
-   echo ""
+   usage_batch_before_after
+   usage_job_templates
+   usage_job_depends
+}
 
-  exit 1
+#get options in front 
+while getopts "J" options; do
+ case $options in
+    J ) print_job_templates
+	exit 1;;
+    * ) usage
+	exit 1;;
+ esac
+done
+
+shift $((OPTIND-1))
+
+if [ "$#" -lt 2 ]
+then 
+	usage
+	exit 1
 fi
+
 
 
 output_dir=`realpath $PWD`
@@ -68,12 +95,17 @@ depends=""
 group=0
 singlesubj=""
 testmode=0
+uri=$NEUROGLIA_URI
+SINGULARITY_IMG=
+cc_account=$CC_COMPUTE_ALLOC
 
 scriptname=${pipeline_script##*/} #strip leading path
 echo $scriptname >&2
 
-while getopts "b:a:j:d:gs:t" options; do
+while getopts "Jb:a:j:d:gs:tI:A:N:U:" options; do
  case $options in
+    J ) print_job_templates
+	exit 1;;
     b ) echo "	Setting arguments before subjid:  $OPTARG" >&2
 	before_args=$OPTARG;;
     a ) echo "	Setting arguments after subjid:  $OPTARG" >&2
@@ -88,10 +120,28 @@ while getopts "b:a:j:d:gs:t" options; do
 	group=1;;
     t ) echo "	Using test-mode (no submit jobs)" >&2
 	testmode=1;;
+    N ) echo "	Using job name: $OPTARG" >&2
+	scriptname=$OPTARG;;
+    I ) echo "	Using SINGULARITY_IMG: $OPTARG" >&2
+	SINGULARITY_IMG=$OPTARG;;
+    U ) echo "  Using singlarity image uri: $OPTARG" >&2
+	uri=$OPTARG;;
+    A ) echo "	Using allocation account: $OPTARG" >&2
+	    cc_account=$OPTARG;;
     * ) usage
 	exit 1;;
  esac
 done
+
+if [ ! -n "$SINGULARITY_IMG" ]
+then
+  SINGULARITY_IMG=`shub-cache $uri`
+  if [ ! "$?" = 0 ]
+  then
+    echo "error loading $uri, exiting!"
+    exit 
+  fi
+fi
 
 
 #check subjlist validity and get # of subjects
@@ -136,11 +186,10 @@ mkdir -p $job_dir
 
 job=$job_dir/$scriptname.job
 
-execpath=`dirname $0`
-execpath=`realpath $execpath`
-cp $execpath/job-templates/${job_template}.job $job  
+cp ${NEUROGLIA_DIR}/job-templates/${job_template}.job $job  
 
 echo "#SBATCH --job-name=$scriptname" >> $job
+echo "#SBATCH --account=$cc_account" >> $job
 
 
 if [ "$group" == 0 ]
@@ -153,9 +202,10 @@ then
 	echo "mkdir -p \$SCRATCH_DIR" >> $job
 	echo "subj=\`head -n \$SLURM_ARRAY_TASK_ID `realpath $subjlist`  | tail -n 1\`" >> $job
 	echo cd `pwd` >> $job
+	echo "echo SINGULARITY_IMG: $SINGULARITY_IMG" >> $job
 	echo "echo CMD: $pipeline_script $before_args \$subj $after_args" >>$job
 	echo "echo START_TIME: \`date\`" >>$job
-	echo $pipeline_script $before_args \$subj $after_args  >> $job
+	echo singularity exec $SINGULARITY_OPTS $SINGULARITY_IMG $pipeline_script $before_args \$subj $after_args  >> $job
 	echo "RETURNVAL=\$?" >> $job
 	echo "rm -rf \$SCRATCH_DIR" >> $job
 	echo "echo RETURNVAL=\$RETURNVAL" >>$job
@@ -170,10 +220,11 @@ else
 
 	echo "export SCRATCH_DIR=/scratch/${USER}/\${SLURM_JOB_ID}" >> $job
 	echo "mkdir -p \$SCRATCH_DIR" >> $job
+	echo "echo SINGULARITY_IMG: $SINGULARITY_IMG" >> $job
 	echo "echo CMD: $pipeline_script $before_args `realpath $subjlist` $after_args" >>$job
 	echo "echo START_TIME: \`date\`" >>$job
 	echo cd `pwd` >> $job
-	echo $pipeline_script $before_args `realpath $subjlist` $after_args >> $job
+	echo singularity exec $SINGULARITY_OPTS $SINGULARITY_IMG $pipeline_script $before_args `realpath $subjlist` $after_args >> $job
 	echo "RETURNVAL=\$?" >> $job
 	echo "rm -rf \$SCRATCH_DIR" >> $job
 	echo "echo RETURNVAL=\$RETURNVAL" >>$job
diff --git a/bin/neurogliaSubmit b/bin/neurogliaSubmit
--- a/bin/neurogliaSubmit
+++ b/bin/neurogliaSubmit
@@ -1,5 +1,17 @@
 #!/bin/bash
 
+execpath=`dirname $0`
+execpath=`realpath $execpath`
+
+
+source ${NEUROGLIA_BASH_LIB}
+if [ ! "$?" = 0 ]
+then
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
+fi
+
+
 function usage {
 
    echo""
@@ -13,47 +25,21 @@ function usage {
    echo "optional flags:"
    echo ""
    echo " -t : test-mode, don/'t actually submit any jobs"
-   echo " -n : ninja-mode, delete job file and hide command in log file (for passwords in getDicomTgz)"
+   echo " -n : ninja-mode, delete job file and hide command in log file"
+   echo " -r : run-mode, use singularity run instead of singularity exec"
+   echo " -U <uri> : uri for singularity container to use (default: $NEUROGLIA_URI)"
+   echo " -I <simg> : path to container to use (default: `shub-cache $NEUROGLIA_URI`)"
+   echo " -N <name> : name the batch job (default: name is command with path stripped off)"
+   echo " -A <account> : account to use for allocation (default: $CC_COMPUTE_ALLOC)"
    echo ""
-   echo " Required resources:"
-   echo " -j <job-template> :  sets requested resources"
-   echo "	Regular (default):	8core/32gb/24h"
-   echo "	LongSkinny:		1core/4gb/72h"
-   echo "	ShortFat:		32core/128gb/3h"
-   echo ""
-   echo ""
-   echo " SLURM Job dependencies for pipelining (man sbatch for more details):"
-   echo "  -d aftercorr:jobid[:jobid]	: each subj depends on completed subj in submitted job ids"  
-   echo "  -d afterok:jobid[:jobid]	: each subj depends on all completed subj in submitted job id"
-   echo ""
-
+   usage_job_templates
+   usage_job_depends
 
 }
-
-host=`hostname`
-if [ ! ${host:0:3} = "gra" ]
-then
-	echo "Please ssh to graham.sharcnet.ca before using $0" >&2
-	exit 1
-fi
-
 
 
 #run a pipeline job on the cluster
 #pipeline jobs take subjids as args
-
-if [ ! -n "$SINGULARITY_IMG" ]
-then
-	echo "SINGULARITY_IMG not defined! exiting..." >&2
-	exit 1
-fi
-
-if [ ! -n "$SINGULARITY_OPTS" ]
-then
-	echo "SINGULARITY_OPTS not defined! exiting..." >&2
-	exit 1
-fi
-
 cmd=$0
 cmdname=${cmd##*/}
 
@@ -70,11 +56,16 @@ testmode=0
 enable_wait=0
 ninja=0
 scmd="exec"
-
+uri=$NEUROGLIA_URI
+SINGULARITY_IMG=
 output_dir=`realpath $PWD`
+scriptname=
+cc_account=$CC_COMPUTE_ALLOC
 
-while getopts "j:d:tWnrN:I:" options; do
+while getopts "Jj:d:tWnrN:I:A:U:" options; do
  case $options in
+    J ) print_job_templates
+	exit 1;;
     j ) echo "	Using job template: $OPTARG" >&2
 	job_template=$OPTARG;;
     d ) echo "	Using dependencies: $OPTARG" >&2
@@ -88,10 +79,13 @@ while getopts "j:d:tWnrN:I:" options; do
     r ) echo "  Run instead of exec" >&2
 	scmd="run";;
     N ) echo "	Using job name: $OPTARG" >&2
-	cmdname=$OPTARG;;
+	scriptname=$OPTARG;;
     I ) echo "	Using SINGULARITY_IMG: $OPTARG" >&2
 	SINGULARITY_IMG=$OPTARG;;
-
+    U ) echo "  Using singlarity image uri: $OPTARG" >&2
+	uri=$OPTARG;;
+    A ) echo "	Using allocation account: $OPTARG" >&2
+	    cc_account=$OPTARG;;
     * ) usage
 	exit 1;;
  esac
@@ -100,27 +94,37 @@ done
 
 shift $((OPTIND-1))
 
-run_cmd=$1
+run_cmd=$@
 
-
-if [ ! -n "$cmdname" ]
+if [ ! -n "$scriptname" ]
 then
-cmdname=${run_cmd##*/} #remove up to leading slash
+scriptname=${run_cmd%%\ *} #remove all but first word
+scriptname=${scriptname##*/} #remove up to leading slash
 fi
 
-echo $cmdname >&2
+echo $scriptname >&2
 
+if [ ! -n "$SINGULARITY_IMG" ]
+then
+  SINGULARITY_IMG=`shub-cache $uri`
+  if [ ! "$?" = 0 ]
+  then
+    echo "error loading $uri, exiting!"
+    exit 
+  fi
+fi
 
 job_dir=$output_dir/jobs
 mkdir -p $job_dir
 
-job=$job_dir/$cmdname.job
+job=$job_dir/$scriptname.job
 
 execpath=`dirname $0`
 execpath=`realpath $execpath`
-cp $execpath/job-templates/${job_template}.job $job  
+cp ${NEUROGLIA_DIR}/job-templates/${job_template}.job $job  
 
 echo "#SBATCH --job-name=$cmdname" >> $job
+echo "#SBATCH --account=$cc_account" >> $job
 echo "#SBATCH --output=$job_dir/${cmdname}.%A.out" >> $job
 echo "echo SINGULARITY_IMG: $SINGULARITY_IMG" >> $job
 if [ "$ninja" = 1 ]
diff --git a/bin/regularSubmit b/bin/regularSubmit
--- a/bin/regularSubmit
+++ b/bin/regularSubmit
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+execpath=`dirname $0`
+execpath=`realpath $execpath`
+
+source ${NEUROGLIA_BASH_LIB}
+if [ ! "$?" = 0 ]
+then
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
+fi
+
+
 function usage {
 
    echo""
@@ -7,36 +18,21 @@ function usage {
    echo "Interface for submitting a single cluster job with singularity"
    echo ""
    echo "--------------------------------------------------------------------------"
-   echo "Usage: $cmdname <optional flags>  <command to run>"
+   echo "Usage: $scriptname <optional flags>  <command to run>"
    echo "--------------------------------------------------------------------------"
    echo ""
    echo "optional flags:"
    echo ""
    echo " -t : test-mode, don/'t actually submit any jobs"
    echo " -n : ninja-mode, delete job file and hide command in log file (for passwords in getDicomTgz)"
-   echo ""
-   echo " Required resources:"
-   echo " -j <job-template> :  sets requested resources"
-   echo "	Regular (default):	8core/32gb/24h"
-   echo "	LongSkinny:		1core/4gb/72h"
-   echo "	ShortFat:		32core/128gb/3h"
+   echo " -A <account> : account to use for allocation (default: $CC_COMPUTE_ALLOC)"
+   echo " -E <env_script>:  script to source for env setup"
    echo ""
    echo ""
-   echo " SLURM Job dependencies for pipelining (man sbatch for more details):"
-   echo "  -d aftercorr:jobid[:jobid]	: each subj depends on completed subj in submitted job ids"  
-   echo "  -d afterok:jobid[:jobid]	: each subj depends on all completed subj in submitted job id"
-   echo ""
-
+   usage_job_templates
+   usage_job_depends
 
 }
-
-host=`hostname`
-if [ ! ${host:0:3} = "gra" ]
-then
-	echo "Please ssh to graham.sharcnet.ca before using $0" >&2
-	exit 1
-fi
-
 
 
 #run a pipeline job on the cluster
@@ -53,11 +49,15 @@ depends=""
 testmode=0
 enable_wait=0
 ninja=0
-
+cc_account=$CC_COMPUTE_ALLOC
+scriptname=
 output_dir=`realpath $PWD`
+envscript=
 
-while getopts "j:d:tWnN:" options; do
+while getopts "Jj:d:tWnN:A:E:" options; do
  case $options in
+    J ) print_job_templates
+	exit 1;;
     j ) echo "	Using job template: $OPTARG" >&2
 	job_template=$OPTARG;;
     d ) echo "	Using dependencies: $OPTARG" >&2
@@ -69,7 +69,11 @@ while getopts "j:d:tWnN:" options; do
     n ) echo "  Using ninja mode" >&2
 	ninja=1;;
     N ) echo "	Using job name: $OPTARG" >&2
-	cmdname=$OPTARG;;
+	scriptname=$OPTARG;;
+    A ) echo "	Using allocation account: $OPTARG" >&2
+	    cc_account=$OPTARG;;
+    E ) echo "	Sourcing $OPTARG in each job" >&2
+	envscript=$OPTARG;;
     * ) usage
 	exit 1;;
  esac
@@ -78,29 +82,32 @@ done
 
 shift $((OPTIND-1))
 
-run_cmd=$1
+run_cmd=$@
 
-
-if [ ! -n "$cmdname" ]
+if [ ! -n "$scriptname" ]
 then
-cmdname=${run_cmd##*/} #remove up to leading slash
+scriptname=${run_cmd%%\ *} #remove all but first word
+scriptname=${scriptname##*/} #remove up to leading slash
 fi
 
-
-echo $cmdname >&2
-
+echo $scriptname >&2
 
 job_dir=$output_dir/jobs
 mkdir -p $job_dir
 
-job=$job_dir/$cmdname.job
+job=$job_dir/$scriptname.job
 
-execpath=`dirname $0`
-execpath=`realpath $execpath`
-cp $execpath/job-templates/${job_template}.job $job  
+cp ${NEUROGLIA_DIR}/job-templates/${job_template}.job $job  
 
-echo "#SBATCH --job-name=$cmdname" >> $job
-echo "#SBATCH --output=$job_dir/${cmdname}.%A.out" >> $job
+echo "#SBATCH --job-name=$scriptname" >> $job
+echo "#SBATCH --account=$cc_account" >> $job
+echo "#SBATCH --output=$job_dir/${scriptname}.%A.out" >> $job
+
+if [ -n "$envscript" ]
+then
+	echo "source $envscript" >> $job
+fi
+
 if [ "$ninja" = 1 ]
 then
 echo "echo Ninja-mode - delete job file" >> $job
@@ -136,7 +143,7 @@ else
 	jobid=$(echo ${message} | grep -oh "[1-9][0-9]*$")
 fi
 echo "jobid=$jobid" >&2
-exec_job=$job_dir/$cmdname.$jobid.job
+exec_job=$job_dir/$scriptname.$jobid.job
 
 
 if [ "$ninja" = 0 ]
diff --git a/bin/shub-cache b/bin/shub-cache
--- a/bin/shub-cache
+++ b/bin/shub-cache
@@ -1,15 +1,20 @@
 #!/bin/bash
 
-# Line below locks the script so cannot be run simultaneously (i.e. to prevent conflicts) -- however, does not work on home directory filesystem, only works on project space filesystem...
+execpath=`dirname $0`
+execpath=`realpath $execpath`
 
-#[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :
-
-
-if [ ! -n "$SINGULARITY_DIR" ]
+source ${NEUROGLIA_BASH_LIB}
+if [ ! "$?" = 0 ]
 then
-	echo "SINGULARITY_DIR not set, reverting to default: /project/6007967/akhanf/singularity" >&2
-	export SINGULARITY_DIR=/project/6007967/akhanf/singularity
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
 fi
+
+#if [ ! -n "$SINGULARITY_DIR" ]
+#then
+#	echo "SINGULARITY_DIR not set, reverting to default: /project/6007967/akhanf/singularity" >&2
+#	export SINGULARITY_DIR=/project/6007967/akhanf/singularity
+#fi
 
 if [ ! "$#" = 1 ]
 then
