jobtemplate and opt updates for joblistSubmit

diff --git a/joblistSubmit b/joblistSubmit
--- a/joblistSubmit
+++ b/joblistSubmit
@@ -1,8 +1,18 @@
 #!/bin/bash
 
+execpath=`dirname $0`
+execpath=`realpath $execpath`
 
-if [ "$#" -lt 1 ]
-then 
+
+source $execpath/00_init.sh
+if [ ! "$?" = 0 ]
+then
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
+fi
+
+
+function usage {
    echo""
    echo "=========================================================================="
    echo "Interface for running list of jobs on cluster"
@@ -19,17 +29,27 @@ then
    echo " -e : preserve environment variables (--export=ALL to sbatch)"
    echo " -A <account> : account to use for allocation (default: $CC_COMPUTE_ALLOC)"
    echo ""
-   echo " Required resources:"
-   echo " -j <job-template> :  sets requested resources"
-   echo "	Regular (default):	8core/32gb/24h"
-   echo "	LongSkinny:		1core/4gb/72h"
-   echo "	ShortFat:		32core/128gb/3h"
-   echo ""
-   echo " SLURM Job dependencies for pipelining (man sbatch for more details):"
-   echo "  -d aftercorr:jobid[:jobid]	: each subj depends on completed subj in submitted job ids"  
-   echo "  -d afterok:jobid[:jobid]	: each subj depends on all completed subj in submitted job id"
-   echo ""
+   usage_job_templates
+   usage_job_depends
 
+ }
+
+
+#get options in front 
+while getopts "J" options; do
+ case $options in
+    J ) print_job_templates
+	exit 1;;
+    * ) usage
+	exit 1;;
+ esac
+done
+
+shift $((OPTIND-1))
+
+if [ "$#" -lt 1 ]
+then 
+  usage
   exit 1
 fi
 
@@ -44,8 +64,11 @@ testmode=0
 keepenv=0
 cc_account=$CC_COMPUTE_ALLOC
 
-while getopts "j:td:eA:" options; do
+while getopts "Jj:td:eA:" options; do
  case $options in
+    J ) print_job_templates
+	exit 1;;
+
     j ) echo "	Using job template: $OPTARG" >&2
 	job_template=$OPTARG;;
     d ) echo "	Using dependencies: $OPTARG" >&2
