sourcing init

diff --git a/tar2bids b/tar2bids
--- a/tar2bids
+++ b/tar2bids
@@ -1,8 +1,21 @@
 #!/bin/bash
 
 
+execpath=`dirname $0`
+execpath=`realpath $execpath`
+
+
+source $execpath/00_init.sh
+if [ ! "$?" = 0 ]
+then
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
+fi
+
+
+
 tar2bids_img=`shub-cache docker://khanlab/tar2bids:v0.0.3d`
 
-echo "CMD: singularity run $SINGULARITY_OPTS -B /localscratch:/localscratch $tar2bids_img $@"
-singularity run $SINGULARITY_OPTS -B /localscratch:/localscratch $tar2bids_img $@
+echo "CMD: singularity run $SINGULARITY_OPTS $tar2bids_img $@"
+singularity run $SINGULARITY_OPTS  $tar2bids_img $@
 
diff --git a/validator b/validator
--- a/validator
+++ b/validator
@@ -1,3 +1,15 @@
 #!/bin/bash
 
-singularity run -B /cvmfs:/cvmfs -B /project:/project -B /scratch:/scratch -B /localscratch:/localscratch `shub-cache docker://bids/validator:0.27.10` $@
+execpath=`dirname $0`
+execpath=`realpath $execpath`
+
+
+source $execpath/00_init.sh
+if [ ! "$?" = 0 ]
+then
+	echo "Error initializing neuroglia-helpers, quitting $0"
+	exit 1
+fi
+
+
+singularity run $SINGULARITY_OPTS `shub-cache docker://bids/validator:0.27.10` $@
